### ISSUE TITLE
Migrate from js to ts

### ISSUE THREAD

**Issue by ManuelMaciel** [ManuelMaciel/skyDB#5]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
*feature*

* **What is the current behavior?**
-

* **What is the expected behavior?**
migrate the code from javascript to typescript 

* **What is the motivation / use case for changing the behavior?**
-

* **Please tell us about your environment:**

  - Version: 2.0.0-beta.X
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by diegolikescode** [comment]
Hey @ManuelMaciel, idk if you're doing this already, but if not then I'll do it <3
